### ISSUE TITLE
Seems to report root "input" as a duplicate

### ISSUE THREAD

**Issue by TLATER** [NotAShelf/flint#4]
Hi, this may be a PEBKAC problem, but given [this lockfile](https://github.com/TLATER/dotfiles/blob/master/flake.lock) I get:

```console
ℹ Analyzing 18 unique inputs...
⚠ Found 2 inputs with multiple versions (11 total duplicates)

📋 Detailed Analysis:

(1) root
   ├─ URL: tarball:https://releases.nixos.org/nixos/25.05/nixos-25.05.811339.98ff3f9af268/nixexprs.tar.xz?rev=98ff3f9af2684f6136c24beef08f5e2033fc5389&narHash=sha256-vEN565jtHFJZe82CnbH3VUXS+dtCiLQYf5k5phSps74=
   ├─ Repeats: 11
   ├─ Alias: emacs-overlay
   │     └─ Used by: root
   ├─ Alias: emacs-overlay
   │     └─ Used by: root
   ├─ Alias: famedly-nixos
   │     └─ Used by: root, fenix
   ├─ Alias: flint
   │     └─ Used by: root
   ├─ Alias: root
   ├─ Alias: sops-nix
   │     └─ Used by: root
   ├─ Alias: disko
   │     └─ Used by: root
   ├─ Alias: home-manager
   │     └─ Used by: root
   ├─ Alias: nix-gaming
   │     └─ Used by: root
   ├─ Alias: tree-sitter-sieve
   │     └─ Used by: root
   └─ Alias: fenix
         └─ Used by: famedly-nixos

(2) root
   ├─ URL: github:famedly/famedly-nixos?rev=c888ec16e0ff40a1c534785a4f912cf569a25311&narHash=sha256-6n0lHDigiPimNCVjvFNV3HvN/q32p6f0IOK4jYzV4k8=
   ├─ Repeats: 2
   ├─ Alias: root
   └─ Alias: fenix
         └─ Used by: famedly-nixos

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 Summary:

✗ 2 inputs have duplicate versions
⚠ 11 total duplicate dependencies detected
```

Those inputs are however [duly deduplicated](https://github.com/TLATER/dotfiles/blob/master/flake.nix#L9) and don't show up with separate aliases in the `flake.lock`. The output doesn't seem to really make sense, either, none of these aliases point to `nixpkgs`.

Am I holding it wrong or is this broken?

**Comment by NotAShelf** [comment]
This is interesting, I haven't been able to hit this bug/regression before but it is possible that I messed it up without realizing shortly before 0.3.0.

Currently working on moving flake parsing into a library and tests, I'll try to write some regression tests for this case and resolve it altogether for the next release.

**Comment by NotAShelf** [comment]
Okay, I've spent most of my evening trying to fix this yesterday. I believe [#5](https://github.com/NotAShelf/flint/pull/5) fixes the issue, as I've identified the faulty grouping logic (which, in hindsight, should've been caught earlier) and mostly rewrote the system to be more robust and future-proof. If you could test the PR and see if provides a  correct result for your flake as well, I can merge it and release 0.3.1 today.

**Comment by TLATER** [comment]
Hm, I don't think this is the expected output?

```console
$ nix run github:NotAShelf/flint/notashelf/push-wupznlpvqzuz#flint
🔍 Flint - Dependency Analysis Report
ℹ No inputs found in lockfile
```

It also seems to fail if I flip on `--fail-if-multiple-versions` (I should open another issue about it printing the help menu in that scenario, as an aside), which makes zero sense to me:

```console
$ nix run github:NotAShelf/flint/notashelf/push-wupznlpvqzuz#flint -- --fail-if-multiple-versions
🔍 Flint - Dependency Analysis Report
ℹ No inputs found in lockfile

Error: multiple versions detected: exiting with error as requested
Usage:
  flint [flags]

Examples:
  flint --lockfile=/path/to/flake.lock --verbose
  flint --lockfile=/path/to/flake.lock --output=json
  flint --lockfile=/path/to/flake.lock --output=plain
  flint --merge

Flags:
      --fail-if-multiple-versions   exit with error if multiple versions found
  -h, --help                        help for flint
  -l, --lockfile string             path to flake.lock (default "flake.lock")
  -m, --merge                       merge all dependants into one list for each input
  -o, --output string               output format: plain, pretty, or json (default "pretty")
  -q, --quiet                       suppress all non-error output
  -v, --verbose                     enable verbose output
      --version                     version for flint
```

I've also tried explicitly pointing it at the correct lockfile with `--lockfile`, to be clear.

I've looked through your test cases, though, and I don't understand how I'm running into this with my flake; my lockfile isn't particularly exotic. I guess file reading is running into issues? I have limited experience with go, so debugging further myself is a bit more effort than I'll put in right this instant.

**Comment by NotAShelf** [comment]
I've got an idea to why it's happening, and unlike the lockfile parsing bug this'll (or should) be an easy fix. Kinda busy with something else right now, but I'll get to fixing this as soon as possible. I reckon you can omit the fail flag for the time being to test, though, I'll fix it later today or tomorrow.

**Comment by NotAShelf** [comment]
Should be fixed now, it was a common Cobra gotcha.

I miss Rust...

**Comment by TLATER** [comment]
The superfluous usage print is gone, though I'm still getting a "no inputs" message:

```console
$ nix run github:NotAShelf/flint/notashelf/push-wupznlpvqzuz#flint -- --fail-if-multiple-versions --lockfile ./flake.lock
🔍 Flint - Dependency Analysis Report
ℹ No inputs found in lockfile

Error: multiple versions detected.
 Exiting with error as '--fail-if-multiple-versions' is set
```

Given the code I would expect "No duplicate repositories detected", and no error about multiple versions. I don't expect an error saying "multiple versions detected" immediately after a message saying "No inputs found" either, though at least currently that's probably not an issue I care about; I can see *that* being a problem if someone uses this in a generic org-wide github workflow or something.

Would you like me to split this into three separate issues for tracking purposes? Looks to me like 64c61595d61ea54b121a3233aeaeeb2cdb93485c can already be merged independently.

Thanks for the effort put in here, and yes, I feel you, been stuck doing python work for a bit and I really miss the rust ecosystem's insistence on robust, no-surprises behavior.

**Comment by NotAShelf** [comment]
I'm bound to have some free time tonight, so I'll try to cover everything before I merge the PR; no need to split into more issues.

Thank you for your patience in reporting the issues :)

**Comment by NotAShelf** [comment]
I've went ahead and merged #5 

Been meaning to sneak some feature additions, but I think I'll do those at a later date. Closing as I believe all issues to be fixed, but let me know if there's anything else.

**Comment by TLATER** [comment]
[Works like a charm](https://github.com/TLATER/dotfiles/actions/runs/19115130142/job/54622090519#step:4:428), thanks so much!
